name: Release CI

on:
  push:
    branches:
      - test
    tags:
      - '[0-9]+.*'
  workflow_dispatch:

jobs:
  windows:
    uses: ./.github/workflows/windows-build.yml
    with:
      rime_plugins: hchunhui/librime-lua lotem/librime-octagram rime/librime-predict

  release:
    needs: [windows]
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifact
          merge-multiple: true

      - name: Create Nightly release
        if: ${{ github.repository == 'lotem/librime' && github.ref == 'refs/heads/test' }}
        uses: 'marvinpinto/action-automatic-releases@latest'
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: latest
          prerelease: true
          title: "Nightly Build"
          files: |
            artifact/*

      - name: Create Stable release
        if: ${{ github.ref != 'refs/heads/master' }}
        uses: 'marvinpinto/action-automatic-releases@latest'
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          draft: true
          prerelease: ${{ contains(github.ref_name, '-') }}
          title: librime ${{ github.ref_name }}
          files: |
            artifact/*
